/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTransfersIndexRouteImport } from './routes/_authenticated/transfers/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedScriptsIndexRouteImport } from './routes/_authenticated/scripts/index'
import { Route as AuthenticatedSchedulesIndexRouteImport } from './routes/_authenticated/schedules/index'
import { Route as AuthenticatedNodesIndexRouteImport } from './routes/_authenticated/nodes/index'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups/index'
import { Route as AuthenticatedExecutionsIndexRouteImport } from './routes/_authenticated/executions/index'
import { Route as AuthenticatedAuditIndexRouteImport } from './routes/_authenticated/audit/index'
import { Route as AuthenticatedArtifactsIndexRouteImport } from './routes/_authenticated/artifacts/index'
import { Route as AuthenticatedApplicationsIndexRouteImport } from './routes/_authenticated/applications/index'
import { Route as AuthenticatedAgentsIndexRouteImport } from './routes/_authenticated/agents/index'
import { Route as AuthenticatedTasksNewRouteImport } from './routes/_authenticated/tasks/new'
import { Route as AuthenticatedTasksTaskIdRouteImport } from './routes/_authenticated/tasks/$taskId'
import { Route as AuthenticatedScriptsNewRouteImport } from './routes/_authenticated/scripts/new'
import { Route as AuthenticatedScriptsScriptIdRouteImport } from './routes/_authenticated/scripts/$scriptId'
import { Route as AuthenticatedSchedulesNewRouteImport } from './routes/_authenticated/schedules/new'
import { Route as AuthenticatedSchedulesScheduleIdRouteImport } from './routes/_authenticated/schedules/$scheduleId'
import { Route as AuthenticatedNodesNodeIdRouteImport } from './routes/_authenticated/nodes/$nodeId'
import { Route as AuthenticatedGroupsNewRouteImport } from './routes/_authenticated/groups/new'
import { Route as AuthenticatedGroupsGroupIdRouteImport } from './routes/_authenticated/groups/$groupId'
import { Route as AuthenticatedExecutionsExecutionIdRouteImport } from './routes/_authenticated/executions/$executionId'
import { Route as AuthenticatedArtifactsNewRouteImport } from './routes/_authenticated/artifacts/new'
import { Route as AuthenticatedApplicationsNewRouteImport } from './routes/_authenticated/applications/new'
import { Route as AuthenticatedApplicationsApplicationIdRouteImport } from './routes/_authenticated/applications/$applicationId'
import { Route as AuthenticatedAgentsAgentIdRouteImport } from './routes/_authenticated/agents/$agentId'
import { Route as AuthenticatedTasksTaskIdIndexRouteImport } from './routes/_authenticated/tasks/$taskId/index'
import { Route as AuthenticatedTasksTaskIdRunRouteImport } from './routes/_authenticated/tasks/$taskId/run'
import { Route as AuthenticatedTasksTaskIdEditRouteImport } from './routes/_authenticated/tasks/$taskId/edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransfersIndexRoute =
  AuthenticatedTransfersIndexRouteImport.update({
    id: '/transfers/',
    path: '/transfers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScriptsIndexRoute =
  AuthenticatedScriptsIndexRouteImport.update({
    id: '/scripts/',
    path: '/scripts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchedulesIndexRoute =
  AuthenticatedSchedulesIndexRouteImport.update({
    id: '/schedules/',
    path: '/schedules/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNodesIndexRoute = AuthenticatedNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExecutionsIndexRoute =
  AuthenticatedExecutionsIndexRouteImport.update({
    id: '/executions/',
    path: '/executions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditIndexRoute = AuthenticatedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArtifactsIndexRoute =
  AuthenticatedArtifactsIndexRouteImport.update({
    id: '/artifacts/',
    path: '/artifacts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationsIndexRoute =
  AuthenticatedApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsIndexRoute =
  AuthenticatedAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksNewRoute = AuthenticatedTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksTaskIdRoute =
  AuthenticatedTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScriptsNewRoute = AuthenticatedScriptsNewRouteImport.update({
  id: '/scripts/new',
  path: '/scripts/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScriptsScriptIdRoute =
  AuthenticatedScriptsScriptIdRouteImport.update({
    id: '/scripts/$scriptId',
    path: '/scripts/$scriptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchedulesNewRoute =
  AuthenticatedSchedulesNewRouteImport.update({
    id: '/schedules/new',
    path: '/schedules/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchedulesScheduleIdRoute =
  AuthenticatedSchedulesScheduleIdRouteImport.update({
    id: '/schedules/$scheduleId',
    path: '/schedules/$scheduleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNodesNodeIdRoute =
  AuthenticatedNodesNodeIdRouteImport.update({
    id: '/nodes/$nodeId',
    path: '/nodes/$nodeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsNewRoute = AuthenticatedGroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsGroupIdRoute =
  AuthenticatedGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExecutionsExecutionIdRoute =
  AuthenticatedExecutionsExecutionIdRouteImport.update({
    id: '/executions/$executionId',
    path: '/executions/$executionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArtifactsNewRoute =
  AuthenticatedArtifactsNewRouteImport.update({
    id: '/artifacts/new',
    path: '/artifacts/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationsNewRoute =
  AuthenticatedApplicationsNewRouteImport.update({
    id: '/applications/new',
    path: '/applications/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationsApplicationIdRoute =
  AuthenticatedApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsAgentIdRoute =
  AuthenticatedAgentsAgentIdRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksTaskIdIndexRoute =
  AuthenticatedTasksTaskIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTasksTaskIdRoute,
  } as any)
const AuthenticatedTasksTaskIdRunRoute =
  AuthenticatedTasksTaskIdRunRouteImport.update({
    id: '/run',
    path: '/run',
    getParentRoute: () => AuthenticatedTasksTaskIdRoute,
  } as any)
const AuthenticatedTasksTaskIdEditRoute =
  AuthenticatedTasksTaskIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedTasksTaskIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof authSignInRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/applications/new': typeof AuthenticatedApplicationsNewRoute
  '/artifacts/new': typeof AuthenticatedArtifactsNewRoute
  '/executions/$executionId': typeof AuthenticatedExecutionsExecutionIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/groups/new': typeof AuthenticatedGroupsNewRoute
  '/nodes/$nodeId': typeof AuthenticatedNodesNodeIdRoute
  '/schedules/$scheduleId': typeof AuthenticatedSchedulesScheduleIdRoute
  '/schedules/new': typeof AuthenticatedSchedulesNewRoute
  '/scripts/$scriptId': typeof AuthenticatedScriptsScriptIdRoute
  '/scripts/new': typeof AuthenticatedScriptsNewRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdRouteWithChildren
  '/tasks/new': typeof AuthenticatedTasksNewRoute
  '/agents/': typeof AuthenticatedAgentsIndexRoute
  '/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/artifacts/': typeof AuthenticatedArtifactsIndexRoute
  '/audit/': typeof AuthenticatedAuditIndexRoute
  '/executions/': typeof AuthenticatedExecutionsIndexRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/nodes/': typeof AuthenticatedNodesIndexRoute
  '/schedules/': typeof AuthenticatedSchedulesIndexRoute
  '/scripts/': typeof AuthenticatedScriptsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/transfers/': typeof AuthenticatedTransfersIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/tasks/$taskId/edit': typeof AuthenticatedTasksTaskIdEditRoute
  '/tasks/$taskId/run': typeof AuthenticatedTasksTaskIdRunRoute
  '/tasks/$taskId/': typeof AuthenticatedTasksTaskIdIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/': typeof AuthenticatedIndexRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/applications/new': typeof AuthenticatedApplicationsNewRoute
  '/artifacts/new': typeof AuthenticatedArtifactsNewRoute
  '/executions/$executionId': typeof AuthenticatedExecutionsExecutionIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/groups/new': typeof AuthenticatedGroupsNewRoute
  '/nodes/$nodeId': typeof AuthenticatedNodesNodeIdRoute
  '/schedules/$scheduleId': typeof AuthenticatedSchedulesScheduleIdRoute
  '/schedules/new': typeof AuthenticatedSchedulesNewRoute
  '/scripts/$scriptId': typeof AuthenticatedScriptsScriptIdRoute
  '/scripts/new': typeof AuthenticatedScriptsNewRoute
  '/tasks/new': typeof AuthenticatedTasksNewRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/applications': typeof AuthenticatedApplicationsIndexRoute
  '/artifacts': typeof AuthenticatedArtifactsIndexRoute
  '/audit': typeof AuthenticatedAuditIndexRoute
  '/executions': typeof AuthenticatedExecutionsIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/nodes': typeof AuthenticatedNodesIndexRoute
  '/schedules': typeof AuthenticatedSchedulesIndexRoute
  '/scripts': typeof AuthenticatedScriptsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/transfers': typeof AuthenticatedTransfersIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/tasks/$taskId/edit': typeof AuthenticatedTasksTaskIdEditRoute
  '/tasks/$taskId/run': typeof AuthenticatedTasksTaskIdRunRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/_authenticated/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/_authenticated/applications/new': typeof AuthenticatedApplicationsNewRoute
  '/_authenticated/artifacts/new': typeof AuthenticatedArtifactsNewRoute
  '/_authenticated/executions/$executionId': typeof AuthenticatedExecutionsExecutionIdRoute
  '/_authenticated/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/_authenticated/groups/new': typeof AuthenticatedGroupsNewRoute
  '/_authenticated/nodes/$nodeId': typeof AuthenticatedNodesNodeIdRoute
  '/_authenticated/schedules/$scheduleId': typeof AuthenticatedSchedulesScheduleIdRoute
  '/_authenticated/schedules/new': typeof AuthenticatedSchedulesNewRoute
  '/_authenticated/scripts/$scriptId': typeof AuthenticatedScriptsScriptIdRoute
  '/_authenticated/scripts/new': typeof AuthenticatedScriptsNewRoute
  '/_authenticated/tasks/$taskId': typeof AuthenticatedTasksTaskIdRouteWithChildren
  '/_authenticated/tasks/new': typeof AuthenticatedTasksNewRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
  '/_authenticated/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/_authenticated/artifacts/': typeof AuthenticatedArtifactsIndexRoute
  '/_authenticated/audit/': typeof AuthenticatedAuditIndexRoute
  '/_authenticated/executions/': typeof AuthenticatedExecutionsIndexRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/nodes/': typeof AuthenticatedNodesIndexRoute
  '/_authenticated/schedules/': typeof AuthenticatedSchedulesIndexRoute
  '/_authenticated/scripts/': typeof AuthenticatedScriptsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/transfers/': typeof AuthenticatedTransfersIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/tasks/$taskId/edit': typeof AuthenticatedTasksTaskIdEditRoute
  '/_authenticated/tasks/$taskId/run': typeof AuthenticatedTasksTaskIdRunRoute
  '/_authenticated/tasks/$taskId/': typeof AuthenticatedTasksTaskIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/agents/$agentId'
    | '/applications/$applicationId'
    | '/applications/new'
    | '/artifacts/new'
    | '/executions/$executionId'
    | '/groups/$groupId'
    | '/groups/new'
    | '/nodes/$nodeId'
    | '/schedules/$scheduleId'
    | '/schedules/new'
    | '/scripts/$scriptId'
    | '/scripts/new'
    | '/tasks/$taskId'
    | '/tasks/new'
    | '/agents/'
    | '/applications/'
    | '/artifacts/'
    | '/audit/'
    | '/executions/'
    | '/groups/'
    | '/nodes/'
    | '/schedules/'
    | '/scripts/'
    | '/settings/'
    | '/tasks/'
    | '/transfers/'
    | '/users/'
    | '/tasks/$taskId/edit'
    | '/tasks/$taskId/run'
    | '/tasks/$taskId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/'
    | '/agents/$agentId'
    | '/applications/$applicationId'
    | '/applications/new'
    | '/artifacts/new'
    | '/executions/$executionId'
    | '/groups/$groupId'
    | '/groups/new'
    | '/nodes/$nodeId'
    | '/schedules/$scheduleId'
    | '/schedules/new'
    | '/scripts/$scriptId'
    | '/scripts/new'
    | '/tasks/new'
    | '/agents'
    | '/applications'
    | '/artifacts'
    | '/audit'
    | '/executions'
    | '/groups'
    | '/nodes'
    | '/schedules'
    | '/scripts'
    | '/settings'
    | '/tasks'
    | '/transfers'
    | '/users'
    | '/tasks/$taskId/edit'
    | '/tasks/$taskId/run'
    | '/tasks/$taskId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/_authenticated/'
    | '/_authenticated/agents/$agentId'
    | '/_authenticated/applications/$applicationId'
    | '/_authenticated/applications/new'
    | '/_authenticated/artifacts/new'
    | '/_authenticated/executions/$executionId'
    | '/_authenticated/groups/$groupId'
    | '/_authenticated/groups/new'
    | '/_authenticated/nodes/$nodeId'
    | '/_authenticated/schedules/$scheduleId'
    | '/_authenticated/schedules/new'
    | '/_authenticated/scripts/$scriptId'
    | '/_authenticated/scripts/new'
    | '/_authenticated/tasks/$taskId'
    | '/_authenticated/tasks/new'
    | '/_authenticated/agents/'
    | '/_authenticated/applications/'
    | '/_authenticated/artifacts/'
    | '/_authenticated/audit/'
    | '/_authenticated/executions/'
    | '/_authenticated/groups/'
    | '/_authenticated/nodes/'
    | '/_authenticated/schedules/'
    | '/_authenticated/scripts/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/transfers/'
    | '/_authenticated/users/'
    | '/_authenticated/tasks/$taskId/edit'
    | '/_authenticated/tasks/$taskId/run'
    | '/_authenticated/tasks/$taskId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transfers/': {
      id: '/_authenticated/transfers/'
      path: '/transfers'
      fullPath: '/transfers/'
      preLoaderRoute: typeof AuthenticatedTransfersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scripts/': {
      id: '/_authenticated/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof AuthenticatedScriptsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedules/': {
      id: '/_authenticated/schedules/'
      path: '/schedules'
      fullPath: '/schedules/'
      preLoaderRoute: typeof AuthenticatedSchedulesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nodes/': {
      id: '/_authenticated/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof AuthenticatedNodesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/executions/': {
      id: '/_authenticated/executions/'
      path: '/executions'
      fullPath: '/executions/'
      preLoaderRoute: typeof AuthenticatedExecutionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/': {
      id: '/_authenticated/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthenticatedAuditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/artifacts/': {
      id: '/_authenticated/artifacts/'
      path: '/artifacts'
      fullPath: '/artifacts/'
      preLoaderRoute: typeof AuthenticatedArtifactsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications/': {
      id: '/_authenticated/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthenticatedApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthenticatedAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/new': {
      id: '/_authenticated/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AuthenticatedTasksNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/$taskId': {
      id: '/_authenticated/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scripts/new': {
      id: '/_authenticated/scripts/new'
      path: '/scripts/new'
      fullPath: '/scripts/new'
      preLoaderRoute: typeof AuthenticatedScriptsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scripts/$scriptId': {
      id: '/_authenticated/scripts/$scriptId'
      path: '/scripts/$scriptId'
      fullPath: '/scripts/$scriptId'
      preLoaderRoute: typeof AuthenticatedScriptsScriptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedules/new': {
      id: '/_authenticated/schedules/new'
      path: '/schedules/new'
      fullPath: '/schedules/new'
      preLoaderRoute: typeof AuthenticatedSchedulesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedules/$scheduleId': {
      id: '/_authenticated/schedules/$scheduleId'
      path: '/schedules/$scheduleId'
      fullPath: '/schedules/$scheduleId'
      preLoaderRoute: typeof AuthenticatedSchedulesScheduleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nodes/$nodeId': {
      id: '/_authenticated/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/nodes/$nodeId'
      preLoaderRoute: typeof AuthenticatedNodesNodeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/new': {
      id: '/_authenticated/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof AuthenticatedGroupsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/$groupId': {
      id: '/_authenticated/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/executions/$executionId': {
      id: '/_authenticated/executions/$executionId'
      path: '/executions/$executionId'
      fullPath: '/executions/$executionId'
      preLoaderRoute: typeof AuthenticatedExecutionsExecutionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/artifacts/new': {
      id: '/_authenticated/artifacts/new'
      path: '/artifacts/new'
      fullPath: '/artifacts/new'
      preLoaderRoute: typeof AuthenticatedArtifactsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications/new': {
      id: '/_authenticated/applications/new'
      path: '/applications/new'
      fullPath: '/applications/new'
      preLoaderRoute: typeof AuthenticatedApplicationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications/$applicationId': {
      id: '/_authenticated/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof AuthenticatedApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/$agentId': {
      id: '/_authenticated/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/$taskId/': {
      id: '/_authenticated/tasks/$taskId/'
      path: '/'
      fullPath: '/tasks/$taskId/'
      preLoaderRoute: typeof AuthenticatedTasksTaskIdIndexRouteImport
      parentRoute: typeof AuthenticatedTasksTaskIdRoute
    }
    '/_authenticated/tasks/$taskId/run': {
      id: '/_authenticated/tasks/$taskId/run'
      path: '/run'
      fullPath: '/tasks/$taskId/run'
      preLoaderRoute: typeof AuthenticatedTasksTaskIdRunRouteImport
      parentRoute: typeof AuthenticatedTasksTaskIdRoute
    }
    '/_authenticated/tasks/$taskId/edit': {
      id: '/_authenticated/tasks/$taskId/edit'
      path: '/edit'
      fullPath: '/tasks/$taskId/edit'
      preLoaderRoute: typeof AuthenticatedTasksTaskIdEditRouteImport
      parentRoute: typeof AuthenticatedTasksTaskIdRoute
    }
  }
}

interface AuthenticatedTasksTaskIdRouteChildren {
  AuthenticatedTasksTaskIdEditRoute: typeof AuthenticatedTasksTaskIdEditRoute
  AuthenticatedTasksTaskIdRunRoute: typeof AuthenticatedTasksTaskIdRunRoute
  AuthenticatedTasksTaskIdIndexRoute: typeof AuthenticatedTasksTaskIdIndexRoute
}

const AuthenticatedTasksTaskIdRouteChildren: AuthenticatedTasksTaskIdRouteChildren =
  {
    AuthenticatedTasksTaskIdEditRoute: AuthenticatedTasksTaskIdEditRoute,
    AuthenticatedTasksTaskIdRunRoute: AuthenticatedTasksTaskIdRunRoute,
    AuthenticatedTasksTaskIdIndexRoute: AuthenticatedTasksTaskIdIndexRoute,
  }

const AuthenticatedTasksTaskIdRouteWithChildren =
  AuthenticatedTasksTaskIdRoute._addFileChildren(
    AuthenticatedTasksTaskIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAgentsAgentIdRoute: typeof AuthenticatedAgentsAgentIdRoute
  AuthenticatedApplicationsApplicationIdRoute: typeof AuthenticatedApplicationsApplicationIdRoute
  AuthenticatedApplicationsNewRoute: typeof AuthenticatedApplicationsNewRoute
  AuthenticatedArtifactsNewRoute: typeof AuthenticatedArtifactsNewRoute
  AuthenticatedExecutionsExecutionIdRoute: typeof AuthenticatedExecutionsExecutionIdRoute
  AuthenticatedGroupsGroupIdRoute: typeof AuthenticatedGroupsGroupIdRoute
  AuthenticatedGroupsNewRoute: typeof AuthenticatedGroupsNewRoute
  AuthenticatedNodesNodeIdRoute: typeof AuthenticatedNodesNodeIdRoute
  AuthenticatedSchedulesScheduleIdRoute: typeof AuthenticatedSchedulesScheduleIdRoute
  AuthenticatedSchedulesNewRoute: typeof AuthenticatedSchedulesNewRoute
  AuthenticatedScriptsScriptIdRoute: typeof AuthenticatedScriptsScriptIdRoute
  AuthenticatedScriptsNewRoute: typeof AuthenticatedScriptsNewRoute
  AuthenticatedTasksTaskIdRoute: typeof AuthenticatedTasksTaskIdRouteWithChildren
  AuthenticatedTasksNewRoute: typeof AuthenticatedTasksNewRoute
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
  AuthenticatedApplicationsIndexRoute: typeof AuthenticatedApplicationsIndexRoute
  AuthenticatedArtifactsIndexRoute: typeof AuthenticatedArtifactsIndexRoute
  AuthenticatedAuditIndexRoute: typeof AuthenticatedAuditIndexRoute
  AuthenticatedExecutionsIndexRoute: typeof AuthenticatedExecutionsIndexRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedNodesIndexRoute: typeof AuthenticatedNodesIndexRoute
  AuthenticatedSchedulesIndexRoute: typeof AuthenticatedSchedulesIndexRoute
  AuthenticatedScriptsIndexRoute: typeof AuthenticatedScriptsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTransfersIndexRoute: typeof AuthenticatedTransfersIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAgentsAgentIdRoute: AuthenticatedAgentsAgentIdRoute,
  AuthenticatedApplicationsApplicationIdRoute:
    AuthenticatedApplicationsApplicationIdRoute,
  AuthenticatedApplicationsNewRoute: AuthenticatedApplicationsNewRoute,
  AuthenticatedArtifactsNewRoute: AuthenticatedArtifactsNewRoute,
  AuthenticatedExecutionsExecutionIdRoute:
    AuthenticatedExecutionsExecutionIdRoute,
  AuthenticatedGroupsGroupIdRoute: AuthenticatedGroupsGroupIdRoute,
  AuthenticatedGroupsNewRoute: AuthenticatedGroupsNewRoute,
  AuthenticatedNodesNodeIdRoute: AuthenticatedNodesNodeIdRoute,
  AuthenticatedSchedulesScheduleIdRoute: AuthenticatedSchedulesScheduleIdRoute,
  AuthenticatedSchedulesNewRoute: AuthenticatedSchedulesNewRoute,
  AuthenticatedScriptsScriptIdRoute: AuthenticatedScriptsScriptIdRoute,
  AuthenticatedScriptsNewRoute: AuthenticatedScriptsNewRoute,
  AuthenticatedTasksTaskIdRoute: AuthenticatedTasksTaskIdRouteWithChildren,
  AuthenticatedTasksNewRoute: AuthenticatedTasksNewRoute,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
  AuthenticatedApplicationsIndexRoute: AuthenticatedApplicationsIndexRoute,
  AuthenticatedArtifactsIndexRoute: AuthenticatedArtifactsIndexRoute,
  AuthenticatedAuditIndexRoute: AuthenticatedAuditIndexRoute,
  AuthenticatedExecutionsIndexRoute: AuthenticatedExecutionsIndexRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedNodesIndexRoute: AuthenticatedNodesIndexRoute,
  AuthenticatedSchedulesIndexRoute: AuthenticatedSchedulesIndexRoute,
  AuthenticatedScriptsIndexRoute: AuthenticatedScriptsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTransfersIndexRoute: AuthenticatedTransfersIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
